### ISSUE TITLE
support params?

### ISSUE THREAD

**Issue by sbtly** [dutzi/react-route-transition#1]
I really want to use this library.

But it doesn't seems to be working with params.

How can I do to make it work like below?
```
from: "/:paramA", 
to: "/:paramA/:paramB"
```

**Comment by dutzi** [comment]
Hm, that’s right! It’s a use case I haven’t handled. I’ll see if I can do it maybe during the weekend.

**Comment by dutzi** [comment]
Ok, so in order to keep this package small, and not bound to react-router, I offer the following solution:

`to` and `from` props will now, besides supporting strings and string array, support regular expressions as well.

That way you can write something like: 

```
to: /\/foo/.*?\/bar/
```

I know it's not ideal, the most ergonomic solution would be to set`to` to `/foo/:baz/bar`, but that means I will have to import `react-router`s `matchPath`, which will:

1. Bind `react-route-transition` to `react-router`
2. Blow the package up

wdyt?

**Comment by sbtly** [comment]
Wow, your feedback is super fast!
I mean it’s totally up to you, but right now that’s enough for my usecase so I’m happy about it 😏 
I’m not sure whether there will be side effects or not.

Btw, if you want to support `react-router` but keep this core library small, how about making a separate react-router branch?

**Comment by dutzi** [comment]
Cool, so `1.0.6` is up in the air, with regex support.

>Btw, if you want to support react-router but keep this core library small, how about making a separate react-router branch?

That's a thought, is it common though? I haven't seen libraries diverge like this before, feels a bit odd.

**Comment by sbtly** [comment]
well I saw some `react-router` related libraries have different branches per different `react-router` versions, but I guess it’s not that common approach. 🤔 

Anyway, params is now supported by regex so I’ll close this issue. Thank you for the fast feedback! 😊
